name: AV DB Build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 */12 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Kaniko build
      uses: aevea/action-kaniko@master
      with:
        image: ${{ secrets.DOCKERHUB_USERNAME }}/clamav4pipeline
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        cache: true
        cache_registry: ${{ secrets.DOCKERHUB_USERNAME }}/clamav4pipeline
