name: AV DB Build

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 */12 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    container: 
      image: gcr.io/kaniko-project/executor:debug
    steps:
    - uses: actions/checkout@v1
    - name: Add GitHub push credentials
      run: echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"${{ secrets.REGISTRY_PUSH_TOKEN }}\"}}}" > /kaniko/.docker/config.json
    - name: Image build
      run:  /kaniko/executor --context . --destination ${HUB_USER}/clamav4pipeline:latest --reproducible --cleanup --force
